###############
# tester workflow for biolink lookup
# powen, 8/30/2021
###############

name: 'test'

on: [push]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9.12", "3.11.3"]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Create environment variables
        run: |
          echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run the tests
        run: |
          python -m pytest tests/
